project_id = "eat-sleep-go"

[api]
enabled = true
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = [
  "http://localhost:3000/**",
  "https://kamkyi.github.io/eat-sleep-go/**"
]

[studio]
enabled = true
